"""Construye un oraculo ANONIMIZADO de formato a partir de archivos PBIX.

El bloque ``objects`` de PBIR es deliberadamente abierto en el esquema de
Microsoft. Este script conserva solo la *forma* observada en exports reales de
Desktop: tipo de visual, familia/grupo/propiedad y claves de los envoltorios.
Todos los valores escalares se sustituyen por tokens de tipo. No se guardan
rutas, hashes, ids, textos, nombres de tablas/campos ni valores del modelo.

Los PBIX de origen se abren exclusivamente en lectura, se copian a un temporal
con nombre neutro y se parsea esa copia. El temporal se elimina al terminar.

Ejemplo:

    python scripts/build_format_objects_corpus.py --recursive \
        --output tests/fixtures/synthetic/format_objects_corpus.json \
        C:/copias_pbix
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from pbip import layout_to_pbir, visual_factory  # noqa: E402
from pbip.pbix_reader import read_pbix  # noqa: E402
from services import format_oracle  # noqa: E402

TOKENS = frozenset({"<boolean>", "<number>", "<string>", "<null>"})
FAMILIES = ("objects", "visualContainerObjects")
# HTML Content es un custom visual, aunque la fabrica lo soporte. Su contrato
# no pertenece al catalogo de visuales integrados de Microsoft.
BUILTIN_TYPES = frozenset(visual_factory.REAL_TYPES) - {
    visual_factory.HTML_CONTENT_TYPE
}
# Un valor de formato puede contener expresiones anidadas. Sus claves son
# palabras del lenguaje PBIR, no datos. La lista cerrada hace que una clave
# dinamica o una extension nueva detenga la extraccion para revision humana en
# vez de filtrarse accidentalmente al fixture publico.
SAFE_WRAPPER_KEYS = frozenset({
    "Aggregation", "Algorithm", "AllRolesRef", "And", "Annotations", "Cases",
    "ColorId", "Column", "Columns", "Comparison", "ComparisonKind",
    "Condition", "Conditional", "Contains", "Direction", "Entity",
    "Expression", "ExpressionName", "Expressions", "FillRule", "From",
    "Function", "In", "IncludeAllTypes", "Input", "ItemName", "Left",
    "Literal", "Max", "Measure", "Min", "Name", "NaturalLanguage",
    "OrderBy", "Output", "PackageName", "PackageType", "Parameters",
    "Percent", "PowerBI.MParameterBehavior", "PowerBI.SQExprEvaluationKind",
    "PowerBI.SQExprTextOperatorOption", "Property", "Query", "RangePercent",
    "ResourcePackageItem", "Right", "Role", "Scope", "ScopedEval", "Select",
    "SelectRef", "Source", "SourceRef", "Subquery", "Table", "ThemeDataColor",
    "Transform", "TransformOutputRoleRef", "TransformTableRef", "Type", "Value",
    "Values", "Version", "Where", "annotation", "axisColor", "cases", "color",
    "data", "dataViewWildcard", "defaultCase", "description", "expr",
    "expression", "filter", "fontFamily", "fontSize", "fontStyle",
    "fontWeight", "hideText", "horizontalTextAlignment", "id", "image",
    "isAutoGenerated", "kind", "layout", "linearGradient2", "linearGradient3",
    "listType", "matchingOption", "max", "metadata", "mid", "min", "name",
    "negativeColor", "nullColoringStrategy", "objectName", "pattern",
    "positiveColor", "propertyIdentifier", "propertyName", "reverseDirection",
    "scaling", "scopeId", "selector", "solid", "strategy", "textRuns",
    "textStyle", "totalMatchingOption", "url", "utterance", "value", "version",
    "verticalAlignment",
})


def _shape(value: Any) -> Any:
    """Sustituye cada hoja por su tipo y conserva solo claves estructurales."""
    if isinstance(value, dict):
        keys = set(value)
        unsafe = sorted(str(key) for key in keys
                        if not isinstance(key, str) or key not in SAFE_WRAPPER_KEYS)
        if unsafe:
            raise ValueError(
                "El valor contiene claves no aprobadas para el corpus publico: "
                + ", ".join(unsafe))
        return {key: _shape(child) for key, child in sorted(value.items())}
    if isinstance(value, list):
        # Un array puede contener variantes. Se conserva una vez cada forma,
        # ordenada por su JSON canonico; nunca sus valores ni su cardinalidad.
        variants: Dict[str, Any] = {}
        for child in value:
            shaped = _shape(child)
            canonical = json.dumps(shaped, ensure_ascii=True,
                                   sort_keys=True, separators=(",", ":"))
            variants[canonical] = shaped
        return [variants[key] for key in sorted(variants)]
    if isinstance(value, bool):
        return "<boolean>"
    if isinstance(value, (int, float)):
        return "<number>"
    if isinstance(value, str):
        return "<string>"
    if value is None:
        return "<null>"
    # PBIR JSON no admite otras hojas. Rechazarlas evita serializar por
    # accidente la representacion de un objeto ajeno al formato.
    raise TypeError(f"Hoja JSON no soportada: {type(value).__name__}")


def _canonical(value: Any) -> str:
    return json.dumps(value, ensure_ascii=True, sort_keys=True,
                      separators=(",", ":"))


def _pbix_files(inputs: Iterable[str], recursive: bool) -> List[Path]:
    found: Dict[str, Path] = {}
    for raw in inputs:
        path = Path(raw).expanduser().resolve()
        candidates = ([path] if path.is_file() else
                      path.rglob("*.pbix") if recursive else path.glob("*.pbix"))
        for candidate in candidates:
            if candidate.is_file() and candidate.suffix.casefold() == ".pbix":
                found[str(candidate).casefold()] = candidate
    return [found[key] for key in sorted(found)]


def _hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _visuals_from_copy(path: Path) -> Tuple[str, List[Dict[str, Any]]]:
    contents = read_pbix(path)
    if contents.report_format == "pbir":
        visuals: List[Dict[str, Any]] = []
        for name, raw in contents.pbir_parts.items():
            if not name.replace("\\", "/").endswith("/visual.json"):
                continue
            visuals.append(json.loads(raw.decode("utf-8-sig")))
        return "pbir", visuals
    if contents.report_format == "layout":
        converted = layout_to_pbir.convert_layout(contents.layout or {})
        visuals = [document for name, document in converted.files.items()
                   if name.replace("\\", "/").endswith("/visual.json")]
        return "layout", visuals
    return contents.report_format, []


def build_corpus(paths: Iterable[Path]) -> Dict[str, Any]:
    """Extrae formas desde copias temporales verificadas byte a byte."""
    seen_types: Set[str] = set()
    property_shapes: Dict[Tuple[str, str, str, str], Set[str]] = defaultdict(set)
    selector_shapes: Dict[Tuple[str, str, str], Set[str]] = defaultdict(set)
    catalogs: Dict[str, Dict[str, Any]] = {}

    files = list(paths)
    with tempfile.TemporaryDirectory(prefix="horizun-format-corpus-") as temp:
        temp_root = Path(temp)
        for index, source in enumerate(files):
            before = _hash(source)
            copied = temp_root / f"source_{index:04d}.pbix"
            shutil.copyfile(source, copied)
            if _hash(copied) != before:
                raise IOError("La copia temporal no coincide con el PBIX de origen.")

            _report_format, visuals = _visuals_from_copy(copied)
            for document in visuals:
                visual = document.get("visual")
                if not isinstance(visual, dict):
                    continue
                visual_type = visual.get("visualType")
                if visual_type not in BUILTIN_TYPES:
                    continue
                if visual_type not in catalogs:
                    catalog = format_oracle._load_catalog(visual_type)  # noqa: SLF001
                    if not isinstance(catalog, dict):
                        raise RuntimeError(
                            "No esta disponible el catalogo oficial de formato "
                            f"para {visual_type!r}; se cancela para no publicar "
                            "claves no verificadas.")
                    catalogs[visual_type] = catalog
                seen_types.add(visual_type)

                for family in FAMILIES:
                    groups = visual.get(family)
                    if not isinstance(groups, dict):
                        continue
                    catalog_scope = ("visualObjects" if family == "objects"
                                     else "visualContainerObjects")
                    official_groups = catalogs[visual_type].get(catalog_scope) or {}
                    for group, entries in groups.items():
                        if not isinstance(group, str) or not isinstance(entries, list):
                            continue
                        official_properties = official_groups.get(group)
                        if not isinstance(official_properties, dict):
                            continue
                        for entry in entries:
                            if not isinstance(entry, dict):
                                continue
                            if "selector" in entry:
                                selector_shapes[(visual_type, family, group)].add(
                                    _canonical(_shape(entry["selector"])))
                            properties = entry.get("properties")
                            if not isinstance(properties, dict):
                                continue
                            for prop, value in properties.items():
                                if isinstance(prop, str) and prop in official_properties:
                                    property_shapes[(visual_type, family, group, prop)].add(
                                        _canonical(_shape(value)))

    by_type: Dict[str, Any] = {}
    for visual_type in sorted(seen_types):
        properties = []
        for (kind, family, group, prop), shapes in sorted(property_shapes.items()):
            if kind == visual_type:
                properties.append({
                    "family": family,
                    "group": group,
                    "property": prop,
                    "shapes": [json.loads(shape) for shape in sorted(shapes)],
                })
        selectors = []
        for (kind, family, group), shapes in sorted(selector_shapes.items()):
            if kind == visual_type:
                selectors.append({
                    "family": family,
                    "group": group,
                    "shapes": [json.loads(shape) for shape in sorted(shapes)],
                })
        by_type[visual_type] = {"properties": properties, "selectors": selectors}

    return {
        "schema_version": 1,
        "anonymization": {
            "leaves": sorted(TOKENS),
            "retained": ["built-in visual type", "format family", "format group",
                         "property name", "wrapper keys"],
            "removed": ["source paths", "source hashes", "visual/page ids",
                        "titles and text", "table/field names", "literal values",
                        "custom visual types", "model data"],
            "path_filter": ("only groups and properties present in the pinned "
                            "Microsoft effective-properties catalog"),
            "unknown_wrapper_keys": "fail closed; never serialize",
        },
        "visual_types": by_type,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="+", help="PBIX o carpetas con PBIX")
    parser.add_argument("--recursive", action="store_true",
                        help="Busca PBIX tambien en subcarpetas")
    parser.add_argument("--output", type=Path, required=True,
                        help="JSON anonimizado que se escribira")
    parser.add_argument("--overwrite", action="store_true",
                        help="Permite reemplazar un corpus existente")
    args = parser.parse_args()

    files = _pbix_files(args.inputs, args.recursive)
    if not files:
        parser.error("No se encontro ningun archivo .pbix.")
    output = args.output.expanduser().resolve()
    if output.exists() and not args.overwrite:
        parser.error(f"El destino ya existe: {output}. Usa --overwrite.")

    corpus = build_corpus(files)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(corpus, ensure_ascii=False, indent=2) + "\n",
                      encoding="utf-8")
    properties = sum(len(entry["properties"])
                     for entry in corpus["visual_types"].values())
    selectors = sum(len(entry["selectors"])
                    for entry in corpus["visual_types"].values())
    print(json.dumps({"ok": True, "output": str(output),
                      "visual_types": len(corpus["visual_types"]),
                      "property_signatures": properties,
                      "selector_signatures": selectors}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
